repos:
- repo: git://github.com/troian/pre-commit-golang
  rev: master
  hooks:
    - id: go-imports
- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v2.1.0
  hooks:
    - id: check-merge-conflict
